### ISSUE TITLE
Frequent "connection timed out" errors

### ISSUE THREAD

**Issue by gbakeman** [Humzaman/removed#2]
Using version 1.5.3 from the Play Store. Often when I try to view a deleted or removed comment, removed will say that pushshift.io was taking too long to respond and has timed out. When I go to visit the website as suggested, it seems to be working just fine. Is removed perhaps misreporting a different error?

**Comment by mirsella** [comment]
same, but it appears everytime for me

**Comment by humzakh** [comment]
This error occurs when the Pushshift API is down. It's unfortunately out of my hands, but it seems the new Pushshift API is much more reliable than it used to be.

Closing this issue for now.
